### ISSUE TITLE
Acho que você esqueceu de adicionar os fontes aqui

### ISSUE THREAD

**Issue by pbalduino** [ihercowitz/horasRC4#1]

**Comment by igorhercowitz** [comment]
a ideia desse cara aqui é somente armazenar o `core` JS do projeto, dando liberdade para quem quiser construir a sua própria interface com HTML e CSS 👍 :)

**Comment by ihercowitz** [comment]
a ideia desse cara aqui é somente armazenar o core JS do projeto, dando liberdade para quem quiser construir a sua própria interface com HTML e CSS 👍 :)

**Comment by pbalduino** [comment]
ou seja, "turn yourself, give your jumps"

**Comment by ihercowitz** [comment]
https://github.com/ihercowitz/horasRC4/issues/1#issuecomment-242170525

nem tanto.... como eu falei, a ideia aqui nao eh ter o frontend e sim ter um exemplo de uso do RC4 em Javascript. 😄
